/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2024-01-03 06:24:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.project.mytechblog.dao.LikeDao;
import com.project.mytechblog.dao.UserDao;
import com.project.mytechblog.entities.Category;
import java.util.ArrayList;
import com.project.mytechblog.entities.Post;
import com.project.mytechblog.helper.ConnectionProvider;
import com.project.mytechblog.dao.PostDao;
import com.project.mytechblog.entities.User;

public final class show_005fblog_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.project.mytechblog.dao.PostDao");
    _jspx_imports_classes.add("com.project.mytechblog.helper.ConnectionProvider");
    _jspx_imports_classes.add("com.project.mytechblog.dao.LikeDao");
    _jspx_imports_classes.add("com.project.mytechblog.entities.Post");
    _jspx_imports_classes.add("com.project.mytechblog.dao.UserDao");
    _jspx_imports_classes.add("com.project.mytechblog.entities.Category");
    _jspx_imports_classes.add("com.project.mytechblog.entities.User");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error_page.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");

    User user = (User)session.getAttribute("currentUser");
    if(user==null){
    	response.sendRedirect("login_page.jsp");
    }
    
      out.write('\r');
      out.write('\n');

int postId = Integer.parseInt(request.getParameter("post_id"));
PostDao dao = new PostDao(ConnectionProvider.getConnection());
Post p = dao.getPostByPostId(postId);

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>");
      out.print( p.getPostTitle() );
      out.write("</title>\r\n");
      out.write("<!--css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"css/mystyle.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".banner-background {\r\n");
      out.write("clip-path: polygon(38% 0, 70% 0%, 100% 0, 100% 87%, 79% 98%, 52% 89%, 0 100%, 0 0);\r\n");
      out.write("}\r\n");
      out.write(".post-title{\r\n");
      out.write("font-weight: 100;\r\n");
      out.write("}\r\n");
      out.write(".post-content{\r\n");
      out.write("font-weight: 100;\r\n");
      out.write("font-size:20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"fb-root\"></div>\r\n");
      out.write("<script async defer crossorigin=\"anonymous\" src=\"https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v18.0\" nonce=\"r2Qzys2G\"></script>\r\n");
      out.write("<!-- navbar -->\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark primary-background\">\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"index.jsp\"><span class = \"fa fa-dashboard\"></span>  Tech Blog</a>\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"profile.jsp\"><span class = \"fa fa-universal-access\"></span>  LearnCode With Soumi <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("          <span class = \"fa fa-check-square-o\"></span>   Categories\r\n");
      out.write("        </a>\r\n");
      out.write("         <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("        ");

       PostDao postd = new PostDao(ConnectionProvider.getConnection());
       ArrayList<Category>list = postd.getAllCategories();
       for(Category c:list)
       {
       
      out.write("\r\n");
      out.write("       <a class=\"dropdown-item\" href=\"#\">");
      out.print( c.getCategoryName() );
      out.write("</a>\r\n");
      out.write("       <div class=\"dropdown-divider\"></div>\r\n");
      out.write("       \r\n");
      out.write("       ");

       }
       
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\"><span class = \"fa fa-address-card-o\"></span>  Contact</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\" data-toggle = \"modal\" data-target = \"#add-post-modal\"><span class = \"fa fa-caret-square-o-right\"></span>  Post</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <ul class=\"navbar-nav mr-right\">\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\"  href = \"#!\"data-toggle = \"modal\" data-target = \"#profile-modal\"><span class = \"fa fa-user-circle\"></span>  ");
      out.print( user.getUserName() );
      out.write("</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"LogoutServlet\"><span class = \"fa fa-sign-out\"></span>  Logout</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- end of navbar -->\r\n");
      out.write("\r\n");
      out.write("<!-- main content of the body -->\r\n");
      out.write("\r\n");
      out.write("<div class = \"container\">\r\n");
      out.write("<div class = \"row my-4\">\r\n");
      out.write("<div class = \"col-md-8 offset-md-2\">\r\n");
      out.write("<div class = \"card\">\r\n");
      out.write("<div class = \"card-header primary-background text-white\">\r\n");
      out.write("<h4 class = \"post-title\">");
      out.print( p.getPostTitle() );
      out.write("</h4>\r\n");
      out.write("</div>\r\n");
      out.write("<div class = \"card-body\">\r\n");
      out.write("<p class = \"post-content\">");
      out.print( p.getPostContent() );
      out.write("</p>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<div class = \"post-code\">\r\n");
      out.write("<code>");
      out.print( p.getPostCode() );
      out.write("</code>\r\n");
      out.write("</div>\r\n");
      out.write("<div class= \"row my-3\">\r\n");
      out.write("<div class = \"col-md-6\">\r\n");
 UserDao ud = new UserDao(ConnectionProvider.getConnection()); 
      out.write("\r\n");
      out.write("<p style = \"font-style:italic; font-weight:bold;font-size:20px\">Author: ");
      out.print( ud.getUserByUserId(p.getUserId()).getUserName() );
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("<div class = \"col-md-6\">\r\n");
      out.write("<p style = \"font-style:italic;font-weight:bold;font-size:20px\">Posted On: ");
      out.print( p.getPostDate().toLocaleString());
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class = \"card-footer\">\r\n");

LikeDao likeDao = new LikeDao (ConnectionProvider.getConnection());


      out.write("\r\n");
      out.write("<a href = \"#!\" onclick = \"insertLike (");
      out.print( p.getPostId());
      out.write(',');
      out.write(' ');
      out.print( user.getUserId());
      out.write(")\" class= \"btn btn-outline-success btn-sm\"><i class = \"fa fa-thumbs-o-up\"></i> <span class = \"like-counter\">");
      out.print( likeDao.countLikeOnPost(p.getPostId()) );
      out.write("</span></a>\r\n");
      out.write("<a href = \"#!\" class = \"btn btn-outline-success btn-sm\"><i class = \"fa fa-commenting-o\"></i> <span>20</span></a>\r\n");
      out.write("<div class=\"fb-page\" data-href=\"http://localhost:8080/mytechblog/show_blog_page.jsp?post_id=6\" data-tabs=\"timeline\" data-width=\"\" data-height=\"\" data-small-header=\"false\" data-adapt-container-width=\"true\" data-hide-cover=\"false\" data-show-facepile=\"true\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- end of main content of the body -->\r\n");
      out.write("\r\n");
      out.write("<!-- add post modal -->\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"add-post-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"addPostModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header primary-background text-white\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Provide Post Details</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("       <form id = \"add-post-form\" action = \"AddPostServlet\" method = \"post\">\r\n");
      out.write("       <div class = \"form-group\">\r\n");
      out.write("       <select name = \"cId\"class = \"form-control\">   \r\n");
      out.write("       <option selected disabled>---Select Post Category---</option>\r\n");
      out.write("       \r\n");
      out.write("       ");

       PostDao postDao = new PostDao(ConnectionProvider.getConnection());
       ArrayList<Category> list2 = postDao.getAllCategories();
       for(Category c:list2)
       {
       
      out.write("\r\n");
      out.write("       \r\n");
      out.write("       <option value = \"");
      out.print( c.getCategoryId() );
      out.write('"');
      out.write('>');
      out.print( c.getCategoryName() );
      out.write("</option>\r\n");
      out.write("       \r\n");
      out.write("       ");

       }
       
      out.write("\r\n");
      out.write("       </select>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class = \"form-group\">\r\n");
      out.write("       <input name = \"postTitle\" type = \"text\" placeholder = \"Enter Post Title\" class = \"form-control\">\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class = \"form-group\">\r\n");
      out.write("       <textarea name = \"postContent\" class = \"form-control\"rows=\"3\" placeholder = \"Enter Post Content\"></textarea>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class = \"form-group\">\r\n");
      out.write("       <textarea name = \"postCode\" class = \"form-control\"rows=\"3\" placeholder = \"Enter Your Program Code (if any)\"></textarea>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class = \"form-group\">\r\n");
      out.write("       <label>Select Your Photo (if any)</label>\r\n");
      out.write("       <br>\r\n");
      out.write("       <input name = \"postPic\" type = \"file\">\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"container text-center\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <button type=\"submit\" class=\"btn primary-background text-white\">Post</button>\r\n");
      out.write("        </div>\r\n");
      out.write("       </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- end of add post modal -->\r\n");
      out.write("<!-- profile modal -->\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"profile-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header primary-background text-white text-center\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Tech Blog</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      <div class = \"container text-center\">\r\n");
      out.write("      <img src =\"profile pics/");
      out.print( user.getUserProfile());
      out.write("\" class = \"img-fluid\" style=\"border-radius:50%; max-width:150px;\">\r\n");
      out.write("      <br>\r\n");
      out.write("        <h5 class=\"modal-title \" id=\"exampleModalLabel\">");
      out.print( user.getUserName() );
      out.write("</h5>\r\n");
      out.write("        <!-- details -->\r\n");
      out.write("        <div id=\"profile-details\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <table class=\"table\">\r\n");
      out.write("  <tbody>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\">ID</th>\r\n");
      out.write("      <td>");
      out.print( user.getUserId() );
      out.write("</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\">Email Address</th>\r\n");
      out.write("      <td>");
      out.print( user.getUserEmail() );
      out.write("</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\">Status</th>\r\n");
      out.write("      <td>");
      out.print( user.getUserAbout() );
      out.write("</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\">Registered on: </th>\r\n");
      out.write("      <td>");
      out.print( user.getRegDate().toString());
      out.write("</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- edit profile -->\r\n");
      out.write("\r\n");
      out.write("<div id = \"profile-edit\" style = \"display:none\">\r\n");
      out.write("<h4 class = \"mt-2\">Please Edit Carefully</h3>\r\n");
      out.write("<form action = \"EditServlet\" method = \"post\" enctype = \"multipart/form-data\">\r\n");
      out.write("<table class = \"table\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td>ID : </td>\r\n");
      out.write("<td>");
      out.print( user.getUserId() );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Email : </td>\r\n");
      out.write("<td><input type = \"email\" class = \"form-control\" name = \"user_email\" value = \"");
      out.print( user.getUserEmail() );
      out.write("\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Name : </td>\r\n");
      out.write("<td><input type = \"text\" class = \"form-control\" name = \"user_name\" value = \"");
      out.print( user.getUserName());
      out.write("\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Password : </td>\r\n");
      out.write("<td><input type = \"password\" class = \"form-control\" name = \"user_password\" value = \"");
      out.print( user.getUserPassword());
      out.write("\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Status : </td>\r\n");
      out.write("<td><textarea rows = \"4\"class = \"form-control\" name = \"user_about\">");
      out.print( user.getUserAbout());
      out.write("</textarea></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>New Profile Photo :</td>\r\n");
      out.write("<td><input type = \"file\" class = \"form-control\" name = \"user_image\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<div class = \"container\">\r\n");
      out.write("<button type = \"submit\" class = \"btn primary-background text-white\">Save</button>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <button id = \"edit-profile-button\" type=\"button\" class=\"btn primary-background text-white\">Edit</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- end of profile modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- javascripts -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\" integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"js/myjs.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js\" integrity=\"sha512-AA1Bzp5Q0K1KanKKmvN/4d3IRKVlv9PYgwFPvm32nPO6QS8yH1HO7LbgB1pgiOxPtfeg5zEn2ba64MUcqJx6CA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	let editStatus = false;\r\n");
      out.write("	\r\n");
      out.write("	$('#edit-profile-button').click(function(){\r\n");
      out.write("		if(editStatus == false)\r\n");
      out.write("			{\r\n");
      out.write("			$(\"#profile-details\").hide()\r\n");
      out.write("			$(\"#profile-edit\").show()\r\n");
      out.write("			editStatus = true;\r\n");
      out.write("			$(this).text(\"Back\")\r\n");
      out.write("			\r\n");
      out.write("			}else{\r\n");
      out.write("				$(\"#profile-details\").show()\r\n");
      out.write("				$(\"#profile-edit\").hide()\r\n");
      out.write("				editStatus = false;\r\n");
      out.write("				$(this).text(\"Edit\")\r\n");
      out.write("			}\r\n");
      out.write("		\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- add post js -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(e){\r\n");
      out.write("	$(\"#add-post-form\").on(\"submit\", function(event){\r\n");
      out.write("		\r\n");
      out.write("		//this code gets called when form is submitted\r\n");
      out.write("		\r\n");
      out.write("		event.preventDefault();\r\n");
      out.write("		console.log(\"you have clicked on submit\")\r\n");
      out.write("		let form = new FormData(this);\r\n");
      out.write("		\r\n");
      out.write("		//now requesting to server\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: \"AddPostServlet\",\r\n");
      out.write("			type: 'POST',\r\n");
      out.write("			data: form,\r\n");
      out.write("			success: function (data, textStatus, jqXHR){\r\n");
      out.write("				//success\r\n");
      out.write("				console.log(data);\r\n");
      out.write("					swal(\"Good job!\", \"Shared Your Post Successfully.\", \"success\");\r\n");
      out.write("				\r\n");
      out.write("			},\r\n");
      out.write("			error: function (jXHR, textStatus, errorThrown){\r\n");
      out.write("				//error\r\n");
      out.write("				swal(\"Error!\", \"Something Went Wrong. Try Again ...\", \"error\");\r\n");
      out.write("			},\r\n");
      out.write("			processData: false,\r\n");
      out.write("			contentType: false\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
