/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2023-09-22 06:49:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mycart.helper.FactoryProvider;
import mycart.helper.Helper;
import mycart.dao.ProductDao;
import mycart.dao.CategoryDao;
import java.util.List;
import mycart.entities.Product;
import mycart.entities.Category;
import mycart.entities.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/components/common_css_js.jsp", Long.valueOf(1672081315266L));
    _jspx_dependants.put("/components/common_modals.jsp", Long.valueOf(1672212794722L));
    _jspx_dependants.put("/components/message.jsp", Long.valueOf(1671815519672L));
    _jspx_dependants.put("/components/navbar.jsp", Long.valueOf(1672231548994L));
    _jspx_dependants.put("/components/errorPage.jsp", Long.valueOf(1671869830047L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("mycart.dao.CategoryDao");
    _jspx_imports_classes.add("mycart.helper.Helper");
    _jspx_imports_classes.add("mycart.dao.ProductDao");
    _jspx_imports_classes.add("mycart.entities.Product");
    _jspx_imports_classes.add("mycart.helper.FactoryProvider");
    _jspx_imports_classes.add("mycart.entities.User");
    _jspx_imports_classes.add("mycart.entities.Category");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>MyCart - Home Page</title>\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<!-- JavaScript -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.3.min.js\" integrity=\"sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"js/script.js\"></script>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');

User user1=(User)session.getAttribute("current-user");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark custom-bg\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<a class=\"navbar-brand\" href=\"index.jsp\">MyCart</a>\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"index.jsp\">Home <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("    \r\n");
      out.write("    <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#!\" data-toggle=\"modal\" data-target=\"#cart\"><i class=\"fa fa-cart-plus\" style=\"font-size:20px;\"></i><span class=\"ml-0 cart-items\">(0)</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("    \r\n");
      out.write("    ");

    if(user1==null){
    	
      out.write("\r\n");
      out.write("    	<li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"login.jsp\">Login</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"register.jsp\">Register</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("    	");

    }
    else{
    	
      out.write("\r\n");
      out.write("    	<li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.print( user1.getUserType().equals("admin")?"admin.jsp":"normal.jsp" );
      out.write('"');
      out.write('>');
      out.print(user1.getUserName() );
      out.write("</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"LogoutServlet\">Logout</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    	");

    	
    }
    
      out.write("\r\n");
      out.write(" \r\n");
      out.write("      </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>");
      out.write('\r');
      out.write('\n');
 
String errorPage = (String)session.getAttribute("errorPage");
if(errorPage!=null)
{
	
      out.write("\r\n");
      out.write("  <div class=\"alert alert-danger alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("  <strong>");
      out.print( errorPage);
      out.write("</strong>\r\n");
      out.write("  <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">\r\n");
      out.write("    <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("  </button>\r\n");
      out.write("  </div>\r\n");

	session.removeAttribute("errorPage");
}

      out.write('\r');
      out.write('\n');
 
String message = (String)session.getAttribute("message");
if(message!=null)
{
	//out.println(message);
	
      out.write("\r\n");
      out.write("  <div class=\"alert alert-success alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("  <strong>");
      out.print(message );
      out.write("</strong>\r\n");
      out.write("  <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">\r\n");
      out.write("    <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("  </button>\r\n");
      out.write("  </div>\r\n");

	session.removeAttribute("message");
}

      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("<div class=\"row mt-3 mx-2\">\r\n");

String cat = request.getParameter("category");
ProductDao dao = new ProductDao(FactoryProvider.getFactory());
List <Product> list = null;
if(cat==null || cat.trim().equals("all")){
	list = dao.getAllProducts();
}else{
	int cid = Integer.parseInt(cat.trim());
	list=dao.getAllProductsById(cid);
}

CategoryDao cdao = new CategoryDao(FactoryProvider.getFactory());
List <Category> clist = cdao.getCategories();

      out.write("\r\n");
      out.write("<!-- show categories -->\r\n");
      out.write("<div class=\"col-md-2\">\r\n");
      out.write("<div class=\"list-group mt-4\">\r\n");
      out.write("<a href=\"index.jsp?category=all\" class=\"list-group-item list-group-item-action active\">\r\n");
      out.write("    All Categories</a>\r\n");

for(Category c:clist){
	if(cat==null||cat.trim().equals("all")){
		
      out.write("\r\n");
      out.write("		<a href=\"index.jsp?category=");
      out.print(c.getCategoryId() );
      out.write("\" class=\"list-group-item list-group-item-action\">");
      out.print(c.getCategoryTitle() );
      out.write("</a>\r\n");
      out.write("		");

	}
	else if(Integer.parseInt(cat.trim())==c.getCategoryId()){
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		<a href=\"index.jsp?category=");
      out.print(c.getCategoryId() );
      out.write("\" class=\"list-group-item list-group-item-action active\">");
      out.print(c.getCategoryTitle() );
      out.write("</a>\r\n");
 }else{
      out.write("\r\n");
      out.write("	<a href=\"index.jsp?category=");
      out.print(c.getCategoryId() );
      out.write("\" class=\"list-group-item list-group-item-action\">");
      out.print(c.getCategoryTitle() );
      out.write("</a>\r\n");
 }
	
}

      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- show products -->\r\n");
      out.write("<div class=\"col-md-10\">\r\n");
      out.write("<!-- row -->\r\n");
      out.write("<div class=\"row mt-4\">\r\n");
      out.write("<div class=\"col-md-12\">\r\n");
      out.write("<div class=\"card-columns\">\r\n");
      out.write("<!-- traversing products -->\r\n");

for(Product p:list){

      out.write("\r\n");
      out.write("<!-- product card -->\r\n");
      out.write("<div class=\"card product-card\">\r\n");
      out.write("<div class=\"container text-center\">\r\n");
      out.write("<img src=\"img\\products\\");
      out.print(p.getpPhoto() );
      out.write("\" style=\"max-height:200px; max-width:90%; width:auto;\" class=\"card-img-top  m-2\"/>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"card-body\">\r\n");
      out.write("<h5 class=\"card-title\">");
      out.print(p.getpName() );
      out.write("</h5>\r\n");
      out.write("<p class=\"card-text\">");
      out.print(Helper.get10Words(p.getpDesc()) );
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"card-footer text-center\">\r\n");
      out.write("<button class=\"btn custom-bg text-white\" onclick=\"add_to_cart(");
      out.print(p.getpId());
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print(p.getpName());
      out.write("' , ");
      out.print(p.getPriceAfterApplyingDiscount() );
      out.write(")\">Add to Cart</button>\r\n");
      out.write("<button class=\"btn btn-outline-success\">&#X20B9; ");
      out.print(p.getPriceAfterApplyingDiscount() );
      out.write("/- <span class=\"text-secondary discount-label\"> &#X20B9; ");
      out.print(p.getpPrice() );
      out.write(' ');
      out.print(p.getpDiscount());
      out.write("% off</span></button>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

}
if(list.size()==0)
{
	out.println("<h3>No item in this category!</h3>");
}


      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Button trigger modal -->\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"cart\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Your Cart</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("       <div class=\"cart-body\">\r\n");
      out.write("       \r\n");
      out.write("       </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary checkout-btn\" onclick=\"goToCheckout()\">Checkout</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"toast\">This is our custom text </div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
